<?php

define('MESSAGE_COACH_TO_ALL_CUSTOMERS', 30);
define('MESSAGE_COACH_TO_REGISTERED_CUSTOMERS', 31);
define('MESSAGE_COACH_TO_SESSION_REGISTERED_CUSTOMERS', 32);
define('MESSAGE_ADMIN_TO_ALL_CUSTOMERS', 40);
define('MESSAGE_ADMIN_TO_ALL_COACHES', 45);


?>