<?php


define('NOTIFICATION_SESSION_CREATE', 10);
define('NOTIFICATION_SESSION_REGISTER', 11);

define('NOTIFICATION_SESSION_UNREGISTER', 12);

define('NOTIFICATION_SESSION_DELETE', 13);
define('NOTIFICATION_SESSION_EDIT', 14);

define('NOTIFICATION_COACH_REGISTER', 14);
define('NOTIFICATION_COACH_UNREGISTER', 14);


